config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :rooms do
    resources :bookings do
      collection do
        get 'status'
      end
    end
  end
  root 'rooms#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  validates :name, presence: true, length: { minimum: 4, maximum: 32}
  validates :start_time, presence: true, allow_nil: false
  validates :end_time, presence: true, allow_nil: false

  validates :start_time, :end_time, overlap: {:scope => 'room_id'}
  validates :end_time, date: { after: :start_time }

  belongs_to :room

  def self.status?(current_room_id)
    status = false
    current_room_bookings = Booking.where(room_id: current_room_id)
    current_room_bookings.each do |booking|
      status = true if booking.start_time <= DateTime.now && DateTime.now <= booking.end_time
    end
    status
  end
end

app/models/room.rb
class Room < ApplicationRecord
  validates :name, uniqueness: true, presence: true, length: { minimum: 4, maximum: 16}

  has_many :bookings, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @room = Room.find(params[:room_id])
    @bookings = @room.bookings
  end

  def new
    @room = Room.find(params[:room_id])
    @booking = Booking.new
  end

  def create
    @room = Room.find(params[:room_id])
    @booking = @room.bookings.new(booking_params)
    if @booking.save
      flash[:success] = 'Booked!'
      redirect_to room_path(@room)
    else
      flash[:alert] = "This booking overlaps others or can't otherwise be created"
      redirect_to new_room_booking_path(@room)
    end
  end

  def show
    @room = Room.find(params[:room_id])
    @booking = Booking.find(params[:id])
  end

  def edit
    @room = Room.find(params[:room_id])
    @booking = Booking.find(params[:id])
  end

  def update
    @room = Room.find(params[:room_id])
    @booking = Booking.find(params[:id])
    if @booking.update(booking_params)
      flash[:success] = 'Booking updated!'
      redirect_to room_path(@room)
    else
      flash[:alert] = "This booking overlaps others or can't otherwise be updated"
      redirect_to edit_room_booking_path(@room, @booking)
    end
  end

  def destroy
    @room = Room.find(params[:room_id])
    @booking = Booking.find(params[:id])
    @booking.destroy
    flash[:success] = 'Booking cancelled!'
    redirect_to room_path(@room)
  end

  def status
    @status = Booking.status?(params[:room_id])
    render :layout => "status_layout"
  end

  private

  def booking_params
    params.require(:booking).permit(:name, :description, :start_time, :end_time, :room_id)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  def index
    @rooms = Room.all
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      flash[:success] = 'Added!'
      redirect_to rooms_path
    else
      flash[:alert] = "This room already exists!"
      # render 'new'
      redirect_to new_room_path
    end
  end

  def show
    @room = Room.find(params[:id])
  end

  def edit
    @room = Room.find(params[:id])
  end

  def update
    @room = Room.find(params[:id])
    @room.update(room_params)
    flash[:success] = 'Room updated!'
    redirect_to rooms_path
  end

  def destroy
    @room = Room.find(params[:id])
    @room.destroy
    flash[:success] = 'Room deleted!'
    redirect_to rooms_path
  end

  private

  def room_params
    params.require(:room).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def alert_for(flash_type)
    {
        :success => 'alert-success',
        :error => 'alert-danger',
        :alert => 'alert-warning',
        :notice => 'alert-info'
    }[flash_type.to_sym] || flash_type.to_s
  end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/bookings/edit.html.haml
%form{"data-toggle" => "validator", :role => "form"}

.container.booking-forms
  .row
    .col-md-12
      %h2#form-title= 'Edit Booking'
  .row
    = form_for [@room, @booking] do |f|
      .col-md-12
        .form-group
          = f.label :name
          = f.text_field :name, :class => 'form-control', placeholder: 'Name of booking', autofocus: true, :required => ""
        .form-group
          = f.label :description
          = f.text_field :description, :class => 'form-control', placeholder: 'Description'
        .form-group
          = f.label :date
          #datetimepicker5.input-group.date
            %input#date{:name => "date", :type => "text", :class => 'form-control', placeholder: 'Date'}/
            %span.input-group-addon
              %span.glyphicon.glyphicon-calendar
        .form-group
          %div.start-time-picker
            %h5='Start time'
            #datetimepicker3
          %div.to
            %p= 'to'
          %div.end-time-picker
            %h5='End time'
            #datetimepicker4
      .col-md-12
        .form-group
          = f.label :end_time
        .form-group
          = f.label :start_time
          #datetimepicker6.input-group.date
            %input#booking_start_time{:name => "booking[start_time]", :type => "text", :class => 'form-control', placeholder: 'Start time', :required => ""}/
            %span.input-group-addon
              %span.glyphicon.glyphicon-calendar
        .form-group
          = f.label :end_time
          #datetimepicker7.input-group.date
            %input#booking_end_time{:name => "booking[end_time]", :type => "text", :class => 'form-control', placeholder: 'End time', :required => ""}/
            %span.input-group-addon
              %span.glyphicon.glyphicon-calendar
        = f.submit 'Update', :class => 'btn btn-primary', :id => 'book-button'

:javascript
  $(function () {
      $('#datetimepicker5').datetimepicker({
          format: 'DD-MM-YYYY',
          minDate: moment()
      });
      $('#datetimepicker3').datetimepicker({
          format: 'HH:mm',
          inline: true,
          useCurrent: true,
        
          stepping: 5
      });
      var d = new Date();

      $('#datetimepicker4').datetimepicker({
          format: 'HH:mm',
          inline: true,

          stepping: 5
      });
        $("#datetimepicker3").on("dp.change", function (e) {
            $('#datetimepicker4').data("DateTimePicker").minDate(e.date);
        });

        $("#datetimepicker3").on("dp.change", function (e) {
          if($('#datetimepicker4').data("DateTimePicker").date() <= e.date){
            $('#datetimepicker4').data("DateTimePicker").date(e.date.add(5, 'minutes'));
          }
        });

      $('#datetimepicker6').datetimepicker({
          format: 'YYYY-MM-DD HH:mm'
      });
      $('#datetimepicker7').datetimepicker({
          format: 'YYYY-MM-DD HH:mm',
          useCurrent: false
      });
      $("#datetimepicker6").on("dp.change", function (e) {
          $('#datetimepicker7').data("DateTimePicker").minDate(e.date);
      });
      $("#datetimepicker7").on("dp.change", function (e) {
          $('#datetimepicker6').data("DateTimePicker").maxDate(e.date);
      });
      $('#datetimepicker3').on('dp.change', function() {
        storeTime()
      });



      $('#date').focus(function(){
        $('#datetimepicker5').datetimepicker('show');
      });

      $('#datetimepicker4').on('dp.change', function() {
        storeTime()
      });

      $('#datetimepicker5').on('dp.change', function() {
        storeTime()
      });

      function storeTime(){
        $('#booking_end_time').val(
          $('#date').val() + ' ' + $('#datetimepicker4 .timepicker-hour').html() + ':' + $('#datetimepicker4 .timepicker-minute').html()
          );
        $('#booking_start_time').val(
          $('#date').val() + ' ' + $('#datetimepicker3 .timepicker-hour').html() + ':' + $('#datetimepicker3 .timepicker-minute').html()
          );
      }
  });

app/views/bookings/index.html.haml
.container
  .row
    .col-md-12
      - if @room.bookings.any?
        - @room.bookings.each do |booking|
          %h2= link_to booking.name, room_booking_path(@room, booking)
          %h4= booking.description
          %h6= booking.start_time.strftime('%e %B %Y, %H:%M')
          %h6= booking.end_time.strftime('%e %B %Y, %H:%M')
      - else
        No bookings yet

app/views/bookings/new.html.haml
%form{"data-toggle" => "validator", :role => "form"}

.container.booking-forms
  .row
    .col-md-12
      %h2#form-title= 'New Booking'
  .row
    = form_for [@room, @booking] do |f|
      .col-md-12
        .form-group
          = f.label :name
          = f.text_field :name, :class => 'form-control', placeholder: 'Name of booking', autofocus: true, :required => ""
        .form-group
          = f.label :description
          = f.text_field :description, :class => 'form-control', placeholder: 'Description'
        .form-group
          = f.label :date
          #datetimepicker5.input-group.date
            %input#date{:name => "date", :type => "text", :class => 'form-control', placeholder: 'Date (dd-mm-yyyy)'}/
            %span.input-group-addon
              %span.glyphicon.glyphicon-calendar
        .form-group
          %div.start-time-picker
            %h5='Start time'
            #datetimepicker3
          %div.to
            %p= 'to'
          %div.end-time-picker
            %h5='End time'
            #datetimepicker4
      .col-md-12
        .form-group
          = f.label :end_time
        .form-group
          = f.label :start_time
          #datetimepicker6.input-group.date
            %input#booking_start_time{:name => "booking[start_time]", :type => "text", :class => 'form-control', placeholder: 'Start time', :required => ""}/
            %span.input-group-addon
              %span.glyphicon.glyphicon-calendar
        .form-group
          = f.label :end_time
          #datetimepicker7.input-group.date
            %input#booking_end_time{:name => "booking[end_time]", :type => "text", :class => 'form-control', placeholder: 'End time', :required => ""}/
            %span.input-group-addon
              %span.glyphicon.glyphicon-calendar
        = f.submit 'Book', :class => 'btn btn-primary', :id => 'book-button'

:javascript
  $(function () {
      $('#datetimepicker5').datetimepicker({
          format: 'DD-MM-YYYY',
          minDate: moment()
      });
      $('#datetimepicker3').datetimepicker({
          format: 'HH:mm',
          inline: true,
          useCurrent: true,

          stepping: 5
      });
      var d = new Date();

      $('#datetimepicker4').datetimepicker({
          format: 'HH:mm',
          inline: true,
      
          stepping: 5
      });
        $("#datetimepicker3").on("dp.change", function (e) {
            $('#datetimepicker4').data("DateTimePicker").minDate(e.date);
        });

        $("#datetimepicker3").on("dp.change", function (e) {
          if($('#datetimepicker4').data("DateTimePicker").date() <= e.date){
            $('#datetimepicker4').data("DateTimePicker").date(e.date.add(5, 'minutes'));
          }
        });

      $('#datetimepicker6').datetimepicker({
          format: 'YYYY-MM-DD HH:mm'
      });
      $('#datetimepicker7').datetimepicker({
          format: 'YYYY-MM-DD HH:mm',
          useCurrent: false
      });
      $("#datetimepicker6").on("dp.change", function (e) {
          $('#datetimepicker7').data("DateTimePicker").minDate(e.date);
      });
      $("#datetimepicker7").on("dp.change", function (e) {
          $('#datetimepicker6').data("DateTimePicker").maxDate(e.date);
      });
      $('#datetimepicker3').on('dp.change', function() {
        storeTime()
      });



      $('#date').focus(function(){
        $('#datetimepicker5').datetimepicker('show');
      });

      $('#datetimepicker4').on('dp.change', function() {
        storeTime()
      });

      $('#datetimepicker5').on('dp.change', function() {
        storeTime()
      });

      function storeTime(){
        $('#booking_end_time').val(
          $('#date').val() + ' ' + $('#datetimepicker4 .timepicker-hour').html() + ':' + $('#datetimepicker4 .timepicker-minute').html()
          );
        $('#booking_start_time').val(
          $('#date').val() + ' ' + $('#datetimepicker3 .timepicker-hour').html() + ':' + $('#datetimepicker3 .timepicker-minute').html()
          );
      }
  });

app/views/bookings/show.html.haml
.container
  .row
    .col-md-4.booking-detail.col-md-offset-4
      %h2.title= @booking.name
      = link_to "<i class='fa fa-pencil'></i> Edit".html_safe , edit_room_booking_path(@room, @booking)
      |
      = link_to "<i class='fa fa-trash'></i> Cancel".html_safe, room_booking_path(@room, @booking), method: :delete
      %h4= @booking.description
      = @booking.start_time.strftime('%e %B %Y, %H:%M')
      = ' - '
      = @booking.end_time.strftime('%H:%M')
      %br
      %br
      = link_to 'Back to all bookings', '/'

app/views/bookings/status.html.haml
- if @status == true
  %div#in-use
    = 'Room in use'
- else
  %div#available
    = 'Room'
    %br
    = 'available'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Majordomo
    %link{:href => "//netdna.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css", :rel => "stylesheet"}/
    %link{:href => "https://fonts.googleapis.com/css?family=Josefin+Slab:400,700%7CRaleway:300,500", :rel => "stylesheet"}/
    %link{:href => "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.js", :rel => "stylesheet"}/
    %link{href: "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css", rel: "stylesheet", integrity: "sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN", crossorigin: "anonymous"}/
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'shared/navigation'
    .container
      -flash.each do |name, msg|
        = content_tag :div, msg, class: [:alert, alert_for(name)]
      = yield
    %script{:crossorigin => "anonymous", :integrity => "sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa", :src => "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"}



%footer
  .container
    .row.vcenter
      .pull-left.col-xs-6
        %p Copyright ©2017 by Edyta Wrobel, Sho Marovatsanga, Stefan Liute, Mica Whitby
      .col-xs-6
        .pull-right
          %a{:href => "#"}
            %i.fa.fa-linkedin-square.fa-icon
          %a{:href => "#"}
            %i.fa.fa-twitter-square.fa-icon
          %a{:href => "#"}
            %i.fa.fa-facebook-square.fa-icon
          %a{:href => "https://github.com/edytawrobel/majordomo"}
            %i.fa.fa-github-square.fa-icon

app/views/layouts/status_layout.html.haml
%html
  %head
    %meta{:content => "60", "http-equiv" => "refresh"}/
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Majordomo
    %link{:href => "//netdna.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css", :rel => "stylesheet"}/
    %link{:href => "https://fonts.googleapis.com/css?family=Josefin+Slab:400,700%7CRaleway:300,500", :rel => "stylesheet"}/
    %link{:href => "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.js", :rel => "stylesheet"}/
    %link{href: "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css", rel: "stylesheet", integrity: "sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN", crossorigin: "anonymous"}/
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    = yield
    %script{:crossorigin => "anonymous", :integrity => "sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa", :src => "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"}

app/views/rooms/edit.html.haml
%form{"data-toggle" => "validator", :role => "form"}

.container.booking-forms
  .row
    .col-md-12
      %h2#form-title= 'Edit Room'
  .row
    = form_for @room do |f|
      .col-md-12
        .form-group
          = f.label :name
          = f.text_field :name, :class => 'form-control', placeholder: 'Name of room', autofocus: true, :required => ""
          = f.submit 'Update', :class => 'btn btn-primary', :id => 'update-button'

app/views/rooms/index.html.haml
.container
  .row
    .col-md-12
      - if @rooms.any?
        - @rooms.each do |room|
          %div.room-calendar
            %h2.room-title= link_to room.name, room_path(room)
            %a{:href => new_room_booking_path(room) }
              %button.btn.btn-primary
                Create booking
                %i.fa.fa-calendar{"aria-hidden" => "true"}
            = week_calendar events: room.bookings do |date, bookings|
              = date
              - bookings.each do |booking|
                %div
                  = link_to booking.name, room_booking_path(room, booking)
                  %br
                  = booking.start_time.strftime('%H:%M')
                  = ' - '
                  = booking.end_time.strftime('%H:%M')
      - else
        %h1 No rooms yet
.container
  .row
    .col-md-12
      %a{:href => new_room_path }
        %button.btn.btn-primary#add-room
          Add room
          %i.fa.fa-plus-circle{"aria-hidden" => "true"}

app/views/rooms/new.html.haml
%form{"data-toggle" => "validator", :role => "form"}

.container.booking-forms
  .row
    .col-md-12
      %h2#form-title= 'New Room'
  .row
    = form_for @room do |f|
      .col-md-12
        .form-group
          = f.label :name
          = f.text_field :name, :class => 'form-control', placeholder: 'Name of room', autofocus: true, :required => ""
          = f.submit 'Add', :class => 'btn btn-primary', :id => 'book-button'

app/views/rooms/show.html.haml
.container.room-calendar
  .row
    .col-md-12
      %h2.title= @room.name
      = link_to "<i class='fa fa-pencil'></i> Edit".html_safe, edit_room_path
      |
      = link_to "<i class='fa fa-trash'></i> Delete".html_safe, room_path, method: :delete
      %br
      %a{:href => new_room_booking_path(@room) }
        %button.btn.btn-primary
          Create booking
          %i.fa.fa-calendar{"aria-hidden" => "true"}
      - if @room.bookings.any?
        = week_calendar events: @room.bookings do |date, bookings|
          = date
          - bookings.each do |booking|
            %div
              = link_to booking.name, room_booking_path(@room, booking)
              %br
              = booking.start_time.strftime('%H:%M')
              = ' - '
              = booking.end_time.strftime('%H:%M')
      - else
        No bookings yet!

app/views/shared/_navigation.html.haml
%nav.navbar.navbar-default{:role => "navigation"}
  .container-fluid
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => "/"} MAJORDOMO
    / Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse

      %ul.nav.navbar-nav.navbar-right
        %li
          %a{:href => new_room_path} Add Room
      -#   %li
      -#     %a{:href => "#"} Link
      -#   %li
      -#     %a{:href => "#"} Link

    / /.navbar-collapse
  / /.container-fluid

app/views/simple_calendar/_calendar.html.haml
.simple-calendar
  .calendar-heading
    = link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view
    %span.calendar-title
      = t('date.month_names')[start_date.month]
      = start_date.year
    = link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view
  %table.table.table-striped
    %thead
      %tr
        - date_range.slice(0, 7).each do |day|
          %th
            = t('date.abbr_day_names')[day.wday]
            = day.strftime('%e %b')
    %tbody
      - date_range.each_slice(7) do |week|
        %tr
          - week.each do |day|
            = content_tag :td, class: calendar.td_classes_for(day) do
              - if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block)
                - capture_haml(day.strftime(''), sorted_events.fetch(day, []), &block)
              - else
                - block.call day, sorted_events.fetch(day, [])

app/views/simple_calendar/_month_calendar.html.haml
.simple-calendar
  .calendar-heading
    = link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view
    %span.calendar-title
      = t('date.month_names')[start_date.month]
      = start_date.year
    = link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view
  %table.table.table-striped
    %thead
      %tr
        - date_range.slice(0, 7).each do |day|
          %th= t('date.abbr_day_names')[day.wday]
    %tbody
      - date_range.each_slice(7) do |week|
        %tr
          - week.each do |day|
            = content_tag :td, class: calendar.td_classes_for(day) do
              - if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block)
                - capture_haml(day, sorted_events.fetch(day, []), &block)
              - else
                - block.call day, sorted_events.fetch(day, [])

app/views/simple_calendar/_week_calendar.html.haml
.simple-calendar
  .calendar-heading
    = link_to t('simple_calendar.previous', default: "<i class='fa fa-chevron-left'></i>".html_safe), calendar.url_for_previous_view
    %span.calendar-title
      Week #{calendar.week_number}
    = link_to t('simple_calendar.next', default: "<i class='fa fa-chevron-right'></i>".html_safe), calendar.url_for_next_view
  %table.table.table-striped
    %thead
      %tr
        - date_range.slice(0, 7).each do |day|
          %th= day.strftime('%a %e %b')
    %tbody
      - date_range.each_slice(7) do |week|
        %tr
          - week.each do |day|
            = content_tag :td, class: calendar.td_classes_for(day) do
              - if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block)
                - capture_haml(day.strftime(''), sorted_events.fetch(day, []), &block)
              - else
                - block.call day, sorted_events.fetch(day, [])